name: EstuSozluk-Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        #cache: 'npm'
    - name: files
      run: ls
    - name: initial
      run: |
        FILECOUNT=$(ls | wc -l)
        if [ $FILECOUNT -ne 2 ]; then
          echo "Failed!"
          exit 1;
        fi
        echo "passed!"
